# Generated by Django 4.0.2 on 2022-02-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asanamodel',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
    ]
